version: '3.8'

networks:
  rva_network:
    name: rva-network
# networks:
#   rva_network:
#     driver: bridge

services:
  node1:
    image: hs60/bsc-chain:latest
    container_name: rva-node1
    volumes:
      - /home/developer/rva-chain/nodes/rva-node1:/root/rva-node
      - ./entry-point.sh:/root/entry-point.sh
    working_dir: /root
    environment:
      - NETWORK_PORT=30306
      - HTTP_PORT=8546
    ports:
      - "8546:8546"
      - "30306:30306"
    entrypoint: [ "sh", "-c", "/root/entry-point.sh" ]  
    # network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30306"]
      interval: 30s
      retries: 5
    networks:
      - rva_network

  node2:
    image: hs60/bsc-chain:latest
    container_name: rva-node2
    volumes:
      - /home/developer/rva-chain/nodes/rva-node2:/root/rva-node
      - ./entry-point.sh:/root/entry-point.sh
    working_dir: /root
    environment:
      - NETWORK_PORT=30307
      - HTTP_PORT=8547
    ports:
      - "8547:8547"
      - "30307:30307"
    entrypoint: [ "sh", "-c", "/root/entry-point.sh" ]  
    # network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30307"]
      interval: 30s
      retries: 5
    networks:
      - rva_network

  node3:
    image: hs60/bsc-chain:latest
    container_name: rva-node3
    volumes:
      - /home/developer/rva-chain/nodes/rva-node3:/root/rva-node
      - ./entry-point.sh:/root/entry-point.sh
    working_dir: /root
    environment:
      - NETWORK_PORT=30308
      - HTTP_PORT=8548
    ports:
      - "8548:8548"
      - "30308:30308"
    entrypoint: [ "sh", "-c", "/root/entry-point.sh" ]  
    # network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30308"]
      interval: 30s
      retries: 5
    networks:
      - rva_network

  node4:
    image: hs60/bsc-chain:latest
    container_name: rva-node4
    volumes:
      - /home/developer/rva-chain/nodes/rva-node4:/root/rva-node
      - ./entry-point.sh:/root/entry-point.sh
    working_dir: /root
    environment:
      - NETWORK_PORT=30309
      - HTTP_PORT=8549
    ports:
      - "8549:8549"
      - "30309:30309"
    entrypoint: [ "sh", "-c", "/root/entry-point.sh" ]  
    # network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30309"]
      interval: 30s
      retries: 5
    networks:
      - rva_network

  node5:
    image: hs60/bsc-chain:latest
    container_name: rva-node5
    volumes:
      - /home/developer/rva-chain/nodes/rva-node5:/root/rva-node
      - ./entry-point.sh:/root/entry-point.sh
    working_dir: /root
    environment:
      - NETWORK_PORT=30310
      - HTTP_PORT=8550
    ports:
      - "8550:8550"
      - "30310:30310"
    entrypoint: [ "sh", "-c", "/root/entry-point.sh" ]  
    # network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30310"]
      interval: 30s
      retries: 5
    networks:
      - rva_network

